### PR TITLE
#done #CU-3u4b2bt zombienet binary and draft runner

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
- zombienet binary(no sandbox)
- draft non nixified runner

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3u4b2bt all in one nixfied runner with zombienet](https://app.clickup.com/t/3u4b2bt)

**Comment by dzmitry-lahoda** [comment]
On CI fails
```
copying path '/nix/store/70xdsvpa77bai9immbq5czmyz9rzldn7-docs-0.0.0-node-modules' from 'https://composable-community.cachix.org/'...
building '/nix/store/xriwm1xjclky3pxdsdv9fjg64rxb7gl9-docs-0.0.0.drv'...
docs> unpacking sources
docs> unpacking source archive /nix/store/gkjqcvrlpvd8wx8yz0iykv07ljq2dzxx-docs
docs> source root is docs
docs> patching sources
docs> configuring
docs> cp: cannot copy a directory, '/nix/store/70xdsvpa77bai9immbq5czmyz9rzldn7-docs-0.0.0-node-modules/npm-cache', into itself, '/tmp/nix-build-docs-0.0.0.drv-0/docs/npm-cache'
error: builder for '/nix/store/xriwm1xjclky3pxdsdv9fjg64rxb7gl9-docs-0.0.0.drv' failed with exit code 1
Stopped watching /nix/store and waiting for queue to empty ...
Done.
compressing and pushing /nix/store/yxw2s2iq7fwbzfxd20kq9md9s1gm11hz-source (123.80 MiB)
Error: Process completed with exit code 1.

```

**Comment by dzmitry-lahoda** [comment]
locally it is awesome

image

**Review by andyjsbell — APPROVED** [review]
lgtm

**Pull request merged**
