### PR TITLE
[CU-2t7r0cb] Integration Tests: Oracle Update

### PR DESCRIPTION
**Pull request by Dom-Roth**
## Issue
https://app.clickup.com/t/2t7r0cb

## Description
The main issue with the old Oracle test was, that we were missing essential queries (e.g. get current price) during the time they were implemented.
Additionally some performance improvements to the test suite.
Updated types.

## Checklist

- [ ] Implemented all tests
- [ ] Implemented all required test checks
- [ ] Cleaned up all code
- [ ] Added required documentation
- [ ] Ran the whole test suite without any failures
- [ ] Ran `npm run lint` without any warnings / errors
- [ ] Created / Updated ClickUp report

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2t7r0cb Integration Tests: [CHECK] Oracle](https://app.clickup.com/t/2t7r0cb)

**Review by SitaramCF — APPROVED** [review]

**Review by kollegian — APPROVED** [review]

**Review by kollegian — APPROVED** [review]

**Comment by Dom-Roth** [comment]
Blocked by: https://app.clickup.com/t/2zfzdpa

**Comment by Dom-Roth** [comment]
Closed in favor of #2892

**Pull request closed without merging**
