### PR TITLE
fix(vamm): Handle `output_amount_limit` correctly when removing asset

### PR DESCRIPTION
**Pull request by Cardosaum**
## Issue
[CU-2rha0dh](https://app.clickup.com/t/2rha0dh)

## Description
There was a misunderstanding while implementing the limit output for cases where the swap *removes* some amount from the Vamm. The checks were updated to take into account this difference.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2rha0dh Re-evaluate slippage controls](https://app.clickup.com/t/2rha0dh)

**Comment by Cardosaum** [comment]
bors try

**Review by 0xangelo — APPROVED** [review]
LGTM! 🚀

**Review by kevin-composable — APPROVED** [review]

**Pull request merged**
