### PR TITLE
[No Ticket] Squash Merge the PRs when Merging

### PR DESCRIPTION
**Pull request by vimukthi-git**
Squash merge the commits to keep the history clean while also allowing easier cherry-picks of features for release.

### CODE REVIEW

**Review by KaiserKarel — APPROVED** [review]
lgtm

**Review by andyjsbell — APPROVED** [review]
thanks @vimukthi-git

**Review by PoisonPhang — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by benluelo — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Comment by vimukthi-git** [comment]
@mergifyio refresh

**Comment by vimukthi-git** [comment]
@mergifyio refresh

**Comment by vimukthi-git** [comment]
https://github.com/Mergifyio refresh

**Pull request merged**
