### PR TITLE
adds cli for generating runtime metadata

### PR DESCRIPTION
**Pull request by seunlanlege**
Use it like so: 

```bash
 ./code/target/release/composable metadata --chain=dali-dev > ./dali.metadata
 subxt codegen --file=dali.metadata | rustfmt --edition=2018 --emit=stdout > dali.rs
```

### CODE REVIEW

**Review by blasrodri — APPROVED** [review]

**Comment by blasrodri** [comment]
@cor

**Comment by blasrodri** [comment]
@seunlanlege how can we get `polkadot`? For that we need to use `ws`?

**Comment by seunlanlege** [comment]
> @seunlanlege how can we get polkadot? For that we need to use ws?

Yes but that changes less often

**Comment by blasrodri** [comment]
> > @seunlanlege how can we get polkadot? For that we need to use ws?
> 
> Yes but that changes less often

how do you suggest we run the polkadot part in our CI?

**Comment by seunlanlege** [comment]
> @seunlanlege how can we get polkadot? For that we need to use ws?

It'll be generated when we upgrade our polkadot version manually

**Comment by dzmitry-lahoda** [comment]
@blasrodri we can run it each time in nix. if dep did not changed, so it will use cache. so you do not write if changed then run. it just runs.

**Pull request merged**
