### PR TITLE
#CU-3wu87yw migrated tech collective pallet data

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

## Additional Changes

- moved upgrades to mod

## Checklist

- automated -  storage upgrade test passed, sim node upgrade passed
- (manual for release) run upgrade flow on locally running chain

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3wu87yw fix data migration after runtime upgrade of dali](https://app.clickup.com/t/3wu87yw)

**Comment by dzmitry-lahoda** [comment]
@vimukthi-git @andyjsbell tagged you as watcher in CU and here.

**Review by andyjsbell — COMMENTED** [review]
How are we planning to test this upgrade?  We will need something along the lines of https://docs.substrate.io/test/check-runtime.  Could this be in a subsequent PR?

**Review by KaiserKarel — APPROVED** [review]

**Comment by KaiserKarel** [comment]
With simnode we cover the try-runtime case, then we have a final sanity check with fork-off-substrate as part of the regular release process, so sufficiently tested then to me.

**Comment by dzmitry-lahoda** [comment]
@mergifyio refresh

**Comment by vimukthi-git** [comment]
@dzmitry-lahoda Thanks for making sure to upgrade the runtime, otherwise this would have broken Picasso

**Pull request merged**
