### PR TITLE
[Merged by Bors] - [CU-2j4v2yq] docs(book/pallet-integration&developer-guides): added page and text for pallet integration

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/2j4v2yq

## Description
- create structure
- add text and image
- link from developer guides to pallet & integration

## Checklist

- [X] I have updated the `SUMMARY.md` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2j4v2yq Structure Pallets & Integrations section on mdbook](https://app.clickup.com/t/2j4v2yq)

**Review by JafarAz — COMMENTED** [review]
I opened it on code spaces. They're currently not showing as subpages to the Pallets & Integrations subpages.
Screenshot 2022-06-29 at 03 19 35
s

**Review by 0xBrainjar2 — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
> I opened it on code spaces. They're currently not showing as subpages to the Pallets & Integrations subpages. <

This will be addressed either as part of resolving merge conflicts or afterwards in a separate PR.

**Review by PoisonPhang — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by JafarAz — APPROVED** [review]
Can you please hide Lending and Liquidations pallets from the mdbook. I am aware It can't be hidden on GitHub but at least for the gitbook it's better to be hidden.

**Comment by Martin-Kiss** [comment]
Will be merged as discussed with @JafarAz, last comment will be addressed in #1277.

**Pull request closed without merging**
