### PR TITLE
#draft #CU-3v0yb6h #CU-3vhy8q9 #CU-3u4b2mw Dz/zombie/acala and friends

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
## Issue

- staging runs on zombienet
- added build of all networks (will reuse next time pr toml generation : ))) )
- https://github.com/paritytech/zombienet/issues/636 

## Additional Changes

- start removing polka launch networks
- updated zombienet

## Checklist

- deploy to staging and see how it works

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3u4b2mw staging runs out of zombinet](https://app.clickup.com/t/3u4b2mw)

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3vhy8q9 track and updated zombienet with fixes  for several items I raised](https://app.clickup.com/t/3vhy8q9)

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3v0yb6h fix karura](https://app.clickup.com/t/3v0yb6h)

**Comment by dzmitry-lahoda** [comment]
reopen as new PR

**Pull request closed without merging**
