### PR TITLE
Remove setup folder

### PR DESCRIPTION
**Pull request by KaiserKarel**

### CODE REVIEW

**Review by dzmitry-lahoda — APPROVED** [review]
So we do not use our oracle anymore as I got it.

**Comment by KaiserKarel** [comment]
> So we do not use our oracle anymore as I got it.

No, but this is an unused script for interacting with the oracle right?

**Comment by dzmitry-lahoda** [comment]
i do not know.

**Review by aeryz — APPROVED** [review]

**Review by obsessed-cake — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@mergifyio refresh

**Pull request merged**
