### PR TITLE
[Merged by Bors] - Fix background blur issue on firefox

### PR DESCRIPTION
**Pull request by easteregg**
## Issue
*Please replace this line with either a link to the ClickUp issue, or a reference to the GitHub issue.*

## Description
*Please replace this line with info that is not in the ClickUp ticket, eg: "also bumps dependency foo version"*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2k552em Picasso - Background blur fix](https://app.clickup.com/t/2k552em)

**Review by saadjhk — APPROVED** [review]

**Review by andresmechali — APPROVED** [review]
🚀 🚀

**Review by saadjhk — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by markostojanovic087 — APPROVED** [review]

**Pull request closed without merging**
