### PR TITLE
[CU-2dvdtxw]: Replaced old pages with new design & adjusted summary accordingly

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/2dvdtxw

## Checklist

~~- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_~~
~~- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_~~

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2dvdtxw Changes to mdbook](https://app.clickup.com/t/2dvdtxw)

**Review by 0xBrainjar2 — DISMISSED** [review]

**Review by cor — DISMISSED** [review]
LGTM

**Comment by Martin-Kiss** [comment]
some previous commits were not signed, should be fixed now thanks to Dzmitry, Cor, and Dom.
Redid some changes i can only imagine i forgot to save before committing.

**Review by 0xBrainjar2 — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
bors ping

**Pull request merged**
