### PR TITLE
[CU-29qn1qa] - remove outdated sections from book

### PR DESCRIPTION
**Pull request by cor**
## Issue
https://app.clickup.com/t/29qn1qa

## Checklist

- [x] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [x] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-29qn1qa Remove outdated sections from book](https://app.clickup.com/t/29qn1qa)

**Review by dzmitry-lahoda — CHANGES_REQUESTED** [review]
please create subtask to move not outdated info into docs before you remove. angular team will handle that

**Comment by cor** [comment]
@dzmitry-lahoda the pages still exist in the git history so they can easily be recovered if needed, but for this deployment marketing requested to get them removed from the docs site today

**Review by 0xBrainjar2 — COMMENTED** [review]
we still need the pieces about the vault strategy + purchase log - would deprecate the crowdloan pieces tho

**Comment by cor** [comment]
> we still need the pieces about the vault strategy + purchase log - would deprecate the crowdloan pieces tho

@0xBrainjar2 I've restored both the vault strategy and the purchase log. For the purchase log, I've made it a top-level document within the picasso parachain since all of the other crowdloan pieces are removed.

**Review by PoisonPhang — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
as discussed, it is good to remove lending stuff, so it should be recreated later somewhere.

also, I images are not lfs.

I am ok with this PR keep going as other are OK and confirmation from somebody (@Martin-Kiss ? ) about lending docs would be good. 

but yeah, better to continue work and ok to merge overall

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by cor** [comment]
Closing this PR as @Martin-Kiss mentioned that all of these have been deleted in another PR.

**Pull request closed without merging**
