### PR TITLE
[Cu-3849d5z] Integration Tests: Democracy refactor

### PR DESCRIPTION
**Pull request by Dom-Roth**
Recreation of #2521

### CODE REVIEW

**Comment by Dom-Roth** [comment]
Can't find the solution to make extrinsics be dynamically changable in these tests, within a reasonable amount of time.
https://github.com/ComposableFi/composable/pull/2521#discussion_r1042064114
cc: @kollegian

**Review by LyonSsS — APPROVED** [review]
Approved

**Review by kollegian — APPROVED** [review]
LGTM

**Comment by Dom-Roth** [comment]
Closed in favor of #2887

**Pull request closed without merging**
