### PR TITLE
[CU-2d4gjrz] Restructure audit page

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/2d4gjrz

## Checklist

~~- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_~~
~~- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_~~

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2d4gjrz Audit page on monorepo](https://app.clickup.com/t/2d4gjrz)

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by cor — APPROVED** [review]
LGTM

**Review by cor — APPROVED** [review]
LGTM

**Pull request merged**
