### PR TITLE
xcvm: simplify instructions handling in interpreter contract

### PR DESCRIPTION
**Pull request by mina86**
XCVMProgram::instructions is a VecDeque.  The simplest way to split it into first element and tail containing the rest of the instruction is to use pop_front method.  In fact, this is a constant-time operation.

However, handle_execute_step does a strange dance where it converts the instructions into an iterator and then collects the iterator into a new VecDeque.  That’s an O(n) operation with an additional allocation.

Simplify the code to use the pop_front instead.

- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] I have linked Zenhub/Github or any other reference item if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [x] I have added at least one reviewer in reviewers list
- [x] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant features and processes required to release into production

### CODE REVIEW

**Comment by mina86** [comment]
@dzmitry-lahoda, low priority but if you have a moment feel free to take a look.

**Comment by blasrodri** [comment]
Are we running XCVM on CI?

**Comment by dzmitry-lahoda** [comment]
no, we do not run

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by mina86** [comment]
> @mina86 did you run xcvm contracts tests? i doubt these part of CI, so need to run manually
> 
> > I have proved that PR has no general regressions of relevant features and processes required to release into production
> 
> just to ensure all as was before (i guess tests could already fail before, hope not :) )

Yeah, I’m kinda confused interpreting the CI results.  Like bunch of them fail but all that GitHub gives me is ‘This job failed’.  That’s not a useful information which I can use to figure out the problem.

**Comment by dzmitry-lahoda** [comment]
@mina86 please press 

image

it is GH queue

**Comment by dzmitry-lahoda** [comment]
@mina86 Your care about this `draft-release-check` job and its dependencies (see needs).  In your case it seem green.

**Pull request merged**
