### PR TITLE
[CU-22bc21g] Add remark check in CI

### PR DESCRIPTION
**Pull request by andor0**
* Added a Remark (`https://github.com/remarkjs/remark-lint`) check in CI
* Updated `*.md` files to pass a Remark check

### CODE REVIEW

**Review by dzmitry-lahoda — DISMISSED** [review]

**Comment by hussein-aitlahcen** [comment]
@andor0 Is this PR still alive?

**Comment by andor0** [comment]
> @andor0 Is this PR still alive?

Yes, I'm waiting for https://github.com/ComposableFi/composable/issues/221.

**Comment by andor0** [comment]
I'm waiting for #480.

**Review by seunlanlege — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-22bc21g Add Remark in CI](https://app.clickup.com/t/22bc21g)

**Pull request merged**
