### PR TITLE
Only comment nix commands on PRs

### PR DESCRIPTION
**Pull request by KaiserKarel**
The current flow tries to comment on merges into main as well, which is impossible and leads to 1 failed job when merging into main.

### CODE REVIEW

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by hussein-aitlahcen** [comment]
@mergifyio refresh

**Comment by hussein-aitlahcen** [comment]
@mergifyio refresh

**Comment by hussein-aitlahcen** [comment]
@mergifyio update

**Comment by hussein-aitlahcen** [comment]
@mergifyio refresh

**Comment by hussein-aitlahcen** [comment]
@mergifyio update

**Comment by hussein-aitlahcen** [comment]
@mergifyio update

**Comment by hussein-aitlahcen** [comment]
@mergifyio requeue

**Comment by hussein-aitlahcen** [comment]
Absolutely no idea why it's not getting merged

**Comment by dzmitry-lahoda** [comment]
image

**Review by haroldsphinx — APPROVED** [review]

**Comment by hussein-aitlahcen** [comment]
@mergifyio refresh

**Pull request merged**
