### PR TITLE
Ben/rustfmt pre commit hook

### PR DESCRIPTION
**Pull request by benluelo**
This PR adds a simple pre-commit hook to run `make style`. It formats the whole repository (as `make style` does) and then re-stages previously staged files.

### CODE REVIEW

**Comment by hussein-aitlahcen** [comment]
Is there an easy way for someone to disable this? If not, I don't think it's a good thing to enforce this kind of stuff when we know the CI will do.

**Comment by benluelo** [comment]
> Is there an easy way for someone to disable this? If not, I don't think it's a good thing to enforce this kind of stuff when we know the CI will do.

I honestly don't see any reason why one would want to disable this, since any non-formatted code will fail CI... however it is fairly trivial to bypass with [--no-verify](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify)

**Comment by KaiserKarel** [comment]
> My main reason for this PR is that my rustfmt is not on nightly, and as such can't use the configurations in the rustfmt.toml; any file I edit has to be re-formatted with the nightly formatter. Perhaps I'm alone in this?

Cargo should pick up the toolchain.toml and use nightly for everything.

**Comment by hussein-aitlahcen** [comment]
> > Is there an easy way for someone to disable this? If not, I don't think it's a good thing to enforce this kind of stuff when we know the CI will do.
> 
> I honestly don't see any reason why one would want to disable this, since any non-formatted code will fail CI... however it is fairly trivial to bypass with [--no-verify](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify)
> 
> My main reason for this PR is that my rustfmt is not on nightly, and as such can't use the configurations in the `rustfmt.toml`; any file I edit has to be re-formatted with the nightly formatter. Perhaps I'm alone in this?

I just fear of commit pre-hooks being run when rebasing and manually fixing conflicts for instance, something I don't want to happen ^_^

**Comment by benluelo** [comment]
> > My main reason for this PR is that my rustfmt is not on nightly, and as such can't use the configurations in the rustfmt.toml; any file I edit has to be re-formatted with the nightly formatter. Perhaps I'm alone in this?
> 
> Cargo should pick up the toolchain.toml and use nightly for everything.

I just checked and mine definitely doesn't; I'll review my setup and see if there's something wrong.

> I just fear of commit pre-hooks being run when rebasing and manually fixing conflicts for instance, something I don't want to happen ^_^.
> More than just that, I tend to havoid having implicit side effect when executing a git command.

Totally fair - I spoke with Karel, and he said we could put it in a `.tools` directory so people can enable it as they see fit (with instructions on how to do so in said directory)
He also told me that `.git` is not synced, which I didn't know, hence the 0 files changed (hah!) I'll move the script I wrote to a new `.tools` directory and add instructions on how to use it :+1:

**Comment by hussein-aitlahcen** [comment]
> > > My main reason for this PR is that my rustfmt is not on nightly, and as such can't use the configurations in the rustfmt.toml; any file I edit has to be re-formatted with the nightly formatter. Perhaps I'm alone in this?
> > 
> > 
> > Cargo should pick up the toolchain.toml and use nightly for everything.
> 
> I just checked and mine definitely doesn't; I'll review my setup and see if there's something wrong.
> 
> > I just fear of commit pre-hooks being run when rebasing and manually fixing conflicts for instance, something I don't want to happen ^_^.
> > More than just that, I tend to havoid having implicit side effect when executing a git command.
> 
> Totally fair - I spoke with Karel, and he said we could put it in a `.tools` directory so people can enable it as they see fit (with instructions on how to do so in said directory) He also told me that `.git` is not synced, which I didn't know, hence the 0 files changed (hah!) I'll move the script I wrote to a new `.tools` directory and add instructions on how to use it 👍

Alright perfect, thanks for considering this :)

**Comment by benluelo** [comment]
I took some liberty with the structure of the directory and documentation, if anything should be done differently please let me know!

**Review by KaiserKarel — APPROVED** [review]
Nice! structure is good as well.

**Review by hussein-aitlahcen — APPROVED** [review]

**Pull request merged**
