### PR TITLE
[Merged by Bors] - [cu-313atpj] Move fNFT to 0006 RFC

### PR DESCRIPTION
**Pull request by vimukthi-git**
Move fNFT to 0006 RFC

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-313atpj Picasso fNFT extension (pallet)](https://app.clickup.com/t/313atpj)

**Review by andresmechali — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Comment by benluelo** [comment]
Bors r+

**Review by dzmitry-lahoda — APPROVED** [review]

**Pull request closed without merging**
