### PR TITLE
docs(assets): added well known composable assets

### PR DESCRIPTION
**Pull request by JafarAz**
Required for merge:
- [ ] `pr-workflow-check / draft-release-check` is ✅ success
- Other rules GitHub shows you, or can be read in [configuration](../terraform/github.com/branches.tf) 

Makes review faster:
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [ ] Linked Zenhub/Github/Slack/etc reference if one exists
- [ ] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [ ] Added reviewer into `Reviewers`
- [ ] I tagged(`@`) or used other form of notification of one person who I think can handle best review of this PR
- [ ] I have proved that PR has no general regressions of relevant features and processes required to release into production
- [ ] Any dependency updates made, was done according guides from relevant dependency
- Clicking all checkboxes 
- Adding detailed description of changes when it feels appropriate (for example when PR is big)

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
@JafarAz  please do `docs(assets): added well known composable assets`,

so same CI will tell you to do.

**Comment by dzmitry-lahoda** [comment]
if you will name your commits like that it will become PR title automatically

image

**Comment by dzmitry-lahoda** [comment]
@JafarAz please rebase on latest main.

**Comment by dzmitry-lahoda** [comment]
new gate was added, but your branch cannot pass that gate as has old broken things

**Review by kkast — APPROVED** [review]

**Pull request merged**
