### PR TITLE
Frontend repos migration

### PR DESCRIPTION
**Pull request by easteregg**
## Issue
https://app.clickup.com/t/2amempv

## Description
Migration for Pablo and Picasso

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by cor** [comment]
160k additions 🔥

**Review by KaiserKarel — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by saadjhk — APPROVED** [review]

**Pull request merged**
