### PR TITLE
[CU-3324puw] docs(book/audits): replace text

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/3324puw

## Description
- replace content of audits page

## Checklist

~~- [ ] I have updated the `SUMMARY.md` to reflect changes made by this PR _(if applicable)_~~

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3324puw Mdbook Changes: Audit Page](https://app.clickup.com/t/3324puw)

**Review by PoisonPhang — APPROVED** [review]
LGTM!

**Review by 0xBrainjar2 — APPROVED** [review]
We need to update the readme file based on comments i gave jafar, otherwise, i will approve

**Comment by Martin-Kiss** [comment]
As requested by Jafar, this will be merged. Content Updates will be implemented with a separate PR.

**Pull request merged**
