### PR TITLE
chore(cosmwasm): refactor contracts

### PR DESCRIPTION
**Pull request by aeryz**
Refactor cosmwasm contracts.

### CODE REVIEW

**Comment by blasrodri** [comment]
@obsessed-cake also for you to take a look. Is this something we need to complete before having CW on the runtimes?

**Review by krl — APPROVED** [review]
Looks good, nothing to note.

**Comment by blasrodri** [comment]
> Looks good, nothing to note.

Merge?

**Comment by dzmitry-lahoda** [comment]
I see it is not relevant anymore

**Pull request closed without merging**
