### PR TITLE
mosaic: add minimum_amount_out to AmmSwapInfo

### PR DESCRIPTION
**Pull request by cor**
## Issue
https://app.clickup.com/t/2jnx4hn

### CODE REVIEW

**Review by benluelo — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Review by benluelo — DISMISSED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Review by benluelo — DISMISSED** [review]

**Comment by cor** [comment]
I need to get approval from @ComposableFi/codespacers , but I am the only member of that group and I cannot approve my own PR... Let's see if bors will be clever enough to see this

**Review by PoisonPhang — APPROVED** [review]

**Comment by cor** [comment]
I'll add @benluelo to @ComposableFi/codespacers for now in order to resolve this.

**Review by benluelo — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Pull request closed without merging**
