### PR TITLE
Add filtering for rustSrc

### PR DESCRIPTION
**Pull request by KaiserKarel**

### CODE REVIEW

**Review by dzmitry-lahoda — COMMENTED** [review]
rust may embeed anything. json for example. build.rs can co sume configs.

**Comment by KaiserKarel** [comment]
> rust may embeed anything. json for example. build.rs can co sume configs.

Then the build will fail, and we can include it in the filter?

**Comment by dzmitry-lahoda** [comment]
yes. build will fail. so imho it is premature optimization.

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by cor — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@mergifyio requeue

**Pull request merged**
