### PR TITLE
fixed subshell call to ensure that CI waits for exit code of integration tests

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

## Description
- fixed case when integration tests failed, but CI was success
- waiting for NPM with hope it exists non zero
- cannot (... & PID=$! |  tee log &) as either PID is not set at all or set to subshell (so what ever you put $! it will not capture what is needed
- so made output to UI via tail (unfortunately errors logs are normal for now)
 - https://composablefinance.slack.com/archives/C03MJD3E8KX/p1661391802137939
 - needs @Dom-Roth help to fix or report issues of integration tests NOTE: as soon as this merged refresh to get pass https://github.com/ComposableFi/composable/pull/1586#pullrequestreview-1103924701

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
@mergigyio refresh

**Comment by dzmitry-lahoda** [comment]
@mergigyio refresh

**Review by Dom-Roth — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
@Mergifyio refresh

**Comment by dzmitry-lahoda** [comment]
@Mergifyio rebase main

**Comment by dzmitry-lahoda** [comment]
dicussion was to migrate to docker compose with depends on script check for read via curl producing blocks, and health check via curl too. it will not be idear, so better.

**Comment by dzmitry-lahoda** [comment]
@Mergifyio rebase

**Comment by dzmitry-lahoda** [comment]
@mergyfyio rebase

**Comment by dzmitry-lahoda** [comment]
@Mergifyio merge main

**Review by Dom-Roth — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Review by alexkdefi — APPROVED** [review]
:+1:

**Comment by dzmitry-lahoda** [comment]
@merifyio refresh

**Pull request merged**
