### PR TITLE
Pablo Front End Fixes

### PR DESCRIPTION
**Pull request by saadjhk**
## Issue
*Please replace this line with either a link to the ClickUp issue, or a reference to the GitHub issue.*

## Description
*Please replace this line with info that is not in the ClickUp ticket, eg: "also bumps dependency foo version"*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by saadjhk** [comment]
Duplicate of
https://github.com/ComposableFi/composable/pull/1404
https://github.com/ComposableFi/composable/pull/1336

**Review by vimukthi-git — APPROVED** [review]

**Review by easteregg — APPROVED** [review]

**Review by alexkdefi — APPROVED** [review]
👍

**Review by Dom-Roth — APPROVED** [review]

**Comment by vimukthi-git** [comment]
@KaiserKarel I'm merging this manually as @saadjhk was unable to get this merged despite trying it for few days with multiple PR attempts. I wonder if we have some CI bottleneck for this PR

**Comment by KaiserKarel** [comment]
> @KaiserKarel I'm merging this manually as @saadjhk was unable to get this merged despite trying it for few days with multiple PR attempts. I wonder if we have some CI bottleneck for this PR

That might indicate that this PR increases CI times to over 2h. To resolve that, we need to increase the timeout in bors.toml, or figure out the root cause. If this PR blocks others after merging, let's revert

**Comment by saadjhk** [comment]
@KaiserKarel id really like to figure out if there's something wrong, is there any way to access logs of bors runs?

As there aren't many major changes other than FE stuff and all CI checks pass as well

**Comment by KaiserKarel** [comment]
> @KaiserKarel id really like to figure out if there's something wrong, is there any way to access logs of bors runs?
> 
> As there aren't many major changes other than FE stuff and all CI checks pass as well

Bors doesn't run anything itself, it will trigger a GitHub action. So if you go to the actions tab, and filter for the check run from Bors, you can find the run logs.

**Pull request merged**
