### PR TITLE
[CU-1v0rzwy] using cumulus based emulator

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Signed-off-by: dzmitry-lahoda <dzmitry@lahoda.pro>

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-1v0rzwy xcmp: replace simulator with emulator in composable](https://app.clickup.com/t/1v0rzwy)

**Comment by hussein-aitlahcen** [comment]
Is this ready?

**Review by andor0 — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]
:+1:

**Comment by dzmitry-lahoda** [comment]
usage code is on branch. 6 out of 12 tests passed.

**Pull request merged**
