### PR TITLE
#legacy #CU-3v0yb6h #CU-3vhy8q9 #CU-3u4b2mw migrated staging to zombienet

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

waiting for merge of other PRs

# Testing

- waits for PRs about preventing reducing risks to switch to be merged

- build and run devnets via nix (native, docker, docker-compose work - composable only and complete)
- ??? staging testing ?

### CODE REVIEW

**Review by vimukthi-git — APPROVED** [review]
LGTM as long as this is verified to work for Picasso locally already.

**Comment by vimukthi-git** [comment]
@dzmitry-lahoda We may need to delay the merge of this until the critical release 2 staging testing is done. cc @andyjsbell @bostercf

**Comment by dzmitry-lahoda** [comment]
@vimukthi-git why?

**Comment by vimukthi-git** [comment]
@dzmitry-lahoda we want to release Pablo on the coming days with staging testing. If staging breaks at the wrong time we will not be able to test.

**Comment by dzmitry-lahoda** [comment]
@hussein-aitlahcen here I removed all MMR usage. it is not needed. so it was not merged before new year and got tons of conflics.

**Comment by dzmitry-lahoda** [comment]
moving for fork

**Pull request closed without merging**
