### PR TITLE
[bors error, new PR] cor/fix sandbox

### PR DESCRIPTION
**Pull request by cor**
bors errored on this one https://github.com/ComposableFi/composable/pull/1262

### CODE REVIEW

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by lily-gabadadze — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by benluelo — APPROVED** [review]

**Review by Dom-Roth — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@cor probably needs a rebase

**Review by alexkdefi — APPROVED** [review]
👍

**Comment by dzmitry-lahoda** [comment]
fixed by other commits afaik. so closing for now.

**Pull request closed without merging**
