### PR TITLE
Update shell.nix

### PR DESCRIPTION
**Pull request by andor0**
## Issue
https://app.clickup.com/t/2a36jxv

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
is nix packaged version works right now? is it possible to improve version upgrade in all places at once or only string replace guide is best possible?

**Comment by andor0** [comment]
> is nix packaged version works right now? is it possible to improve version upgrade in all places at once or only string replace guide is best possible?

yes, we use this version now.
I think, can move settings of rust version to `nix/rust.nix` and use it in `*.nix` files.I try to do it in one of next PRs.

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by hussein-aitlahcen** [comment]
Ideally we should remove the `shell.nix` and add a proper shell in the `flake.nix`

**Review by hussein-aitlahcen — APPROVED** [review]

**Comment by andor0** [comment]
> Ideally we should remove the `shell.nix` and add a proper shell in the `flake.nix`

I will do it in one of next PRs.

**Pull request merged**
