### PR TITLE
[Merged by Bors] - chore(upgrade): v0.9.27

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**

### CODE REVIEW

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Review by Dom-Roth — APPROVED** [review]
LGTM!

**Review by saadjhk — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]

**Comment by seunlanlege** [comment]
Just realized we merged this without simnode or benchmarks @hussein-aitlahcen any reason why?

**Comment by dzmitry-lahoda** [comment]
@seunlanlege PR passed all gates of main. Simnode was not gate. 

Benchmarks  runs on special hardware which fits is SRE task?

**Pull request closed without merging**
