### PR TITLE
[CU-2xjqnxj] Update concurrency group for unittests with coverage

### PR DESCRIPTION
**Pull request by andor0**
## Issue
https://app.clickup.com/t/2xjqnxj

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2xjqnxj Update concurrency group for unittests with coverage](https://app.clickup.com/t/2xjqnxj)

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by andor0** [comment]
@mergify refresh

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by alexkdefi — APPROVED** [review]
👍

**Comment by andor0** [comment]
@mergify refresh

**Pull request merged**
