### PR TITLE
(CU-862j4v7g8) content update composable parachain overview

### PR DESCRIPTION
**Pull request by Martin-Kiss**

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Task linked: [CU-86776hyjn Content Update Composable Parachain](https://app.clickup.com/t/86776hyjn)

**Comment by KaiserKarel** [comment]
Task linked: [CU-862j4v7g8 Composable Parachain Gitbook Page](https://app.clickup.com/t/862j4v7g8)

**Review by KaiserKarel — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
@mergifyio refresh

**Review by Dom-Roth — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
@mergifyio update

**Comment by Martin-Kiss** [comment]
@mergifyio refresh

**Comment by Martin-Kiss** [comment]
@mergifyio refresh

**Comment by Martin-Kiss** [comment]
@mergifyio refresh

**Comment by Martin-Kiss** [comment]
@mergifyio queue

**Comment by Martin-Kiss** [comment]
@mergifyio update

**Comment by Martin-Kiss** [comment]
Closed in favor of #3252 due to CI issue.

**Pull request closed without merging**
