### PR TITLE
test(integration-tests/democracy): Refactoring tests

### PR DESCRIPTION
**Pull request by Dom-Roth**
Recreation of ~~#2521~~ ~~#2781~~ #2887

### CODE REVIEW

**Review by kollegian — APPROVED** [review]
LGTM

**Review by LyonSsS — APPROVED** [review]

**Comment by Dom-Roth** [comment]
@Mergifyio refresh

**Comment by Dom-Roth** [comment]
@Mergifyio queue

**Comment by Dom-Roth** [comment]
@Mergifyio queue

**Comment by Dom-Roth** [comment]
https://github.com/Mergifyio queue

**Comment by Dom-Roth** [comment]
https://github.com/Mergifyio queue

**Comment by Dom-Roth** [comment]
@mergifyio refresh

**Comment by Dom-Roth** [comment]
https://github.com/Mergifyio queue

**Comment by Dom-Roth** [comment]
https://github.com/Mergifyio refresh

**Comment by Dom-Roth** [comment]
https://github.com/Mergifyio queue

**Pull request merged**
