### PR TITLE
Instrumental fix/sync with main

### PR DESCRIPTION
**Pull request by belousm**
## Issue
*[2t1wtj9](https://app.clickup.com/t/2t1wtj9)*

## Description
*Task related to [this issue](https://app.clickup.com/t/2m24e1f). After [this PR](https://github.com/ComposableFi/composable/pull/1333#pullrequestreview-1042759203) was merged, it's now necessary to sync instrumental branch with main.*

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2t1wtj9 Sync with main branch](https://app.clickup.com/t/2t1wtj9)

**Comment by saruman9** [comment]
I can't leave comments for changes because GitHub hangs every time I do it. I will leave links to the code here.

**Comment by saruman9** [comment]
https://github.com/ComposableFi/composable/blob/56bca8f17ee9d67e27c17383a231bf634a1671d1/frame/instrumental-strategy-pablo/src/lib.rs#L324-L396

Why did you comment it out?

**Review by kevin-composable — APPROVED** [review]

**Comment by saruman9** [comment]
Typo I think: `make_proposale` -> `make_proposal`.

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/tests.rs:7:0`: `pallet::Error` is needed?

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/tests.rs:7:0`: `pallet::Error` is needed?

No, delete it

**Comment by belousm** [comment]
> Typo I think: `make_proposale` -> `make_proposal`.

Thanks! Resolved!

**Comment by saruman9** [comment]
Please apply `cargo +nightly fmt` for `instrumental-strategy` pallet.

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/tests.rs:7:0`: I think `#[allow(unused_imports)]` construction is rudimentary.

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:99:78`: the function never return an error (needed to remove `Result<(), ()>`).

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:107:1`: typo in the word `treshold`.

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:109:7`: if you don't need to add or remove elements from the vector, use slice (`&[T]`) or mutable slice (`&mut [T]`) for easier use of the function (no need to create a vector, allocate memory, etc.).

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:121:0`: here will be more suitable `if let Some(...)` construction (`if let Some(votes) = yes_votes {...}`).

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:110:0`: the function never returns an error.

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/lib.rs:202:2`: could you explain the purpose of this event, please?

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/lib.rs:236:43`: some of functions from the `pallet::call` call `deposit_event` method inside themselves, and some give it to other functions (`liquidity_rebalance` for instance). Maybe we can unify it?

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/mock/helpers.rs:121:0`: here will be more suitable `if let Some(...)` construction (`if let Some(votes) = yes_votes {...}`).

Resolved

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/lib.rs:202:2`: could you explain the purpose of this event, please?

Resolved (I used it for debugging)

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/mock/helpers.rs:121:0`: here will be more suitable `if let Some(...)` construction (`if let Some(votes) = yes_votes {...}`).

Resolved

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/lib.rs:236:43`: some of functions from the `pallet::call` call `deposit_event` method inside themselves, and some give it to other functions (`liquidity_rebalance` for instance). Maybe we can unify it?

Sure. Resolved

**Comment by belousm** [comment]
> Resolved

Resolved

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/mock/helpers.rs:110:0`: the function never returns an error.

Resolved

**Comment by saruman9** [comment]
> `frame/instrumental-strategy-pablo/src/mock/helpers.rs:109:7`: if you don't need to add or remove elements from the vector, use slice (`&[T]`) or mutable slice (`&mut [T]`) for easier use of the function (no need to create a vector, allocate memory, etc.).

Still not resolved. You use reference to a `Vec` (`Option<&Vec<AccountId>>`), but I'm talking about reference to a slice (`&[T]` and `&mut [T]`).

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:99:0`: [the same](https://github.com/ComposableFi/composable/pull/1349#issuecomment-1194072987) (`Vec<T>` -> `&[T]`).

**Comment by saruman9** [comment]
`frame/instrumental-strategy-pablo/src/mock/helpers.rs:16:0`: from `cargo check --all-targets`:
```
warning: unused import: `dispatch::DispatchResultWithPostInfo`.
```

**Comment by belousm** [comment]
> `frame/instrumental-strategy-pablo/src/mock/helpers.rs:16:0`: from `cargo check --all-targets`:
> 
> ```
> warning: unused import: `dispatch::DispatchResultWithPostInfo`.
> ```

Resolved

**Comment by belousm** [comment]
> > `frame/instrumental-strategy-pablo/src/mock/helpers.rs:109:7`: if you don't need to add or remove elements from the vector, use slice (`&[T]`) or mutable slice (`&mut [T]`) for easier use of the function (no need to create a vector, allocate memory, etc.).
> 
> Still not resolved. You use reference to a `Vec` (`Option<&Vec<AccountId>>`), but I'm talking about reference to a slice (`&[T]` and `&mut [T]`).

Resolved

**Pull request merged**
