### PR TITLE
Remove stale configs

### PR DESCRIPTION
**Pull request by KaiserKarel**

### CODE REVIEW

**Review by benluelo — APPROVED** [review]

**Review by scglenn — APPROVED** [review]

**Review by obsessed-cake — APPROVED** [review]

**Review by Martin-Kiss — APPROVED** [review]

**Review by aeryz — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@mergifyio refresh

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@mergifyio requeue

**Comment by KaiserKarel** [comment]
@mergifyio queue

**Comment by KaiserKarel** [comment]
@Mergifyio requeue

**Comment by KaiserKarel** [comment]
@mergifyio refresh

**Pull request merged**
