### PR TITLE
[CU-30eeta4] Update paths in the workflow to update weight files

### PR DESCRIPTION
**Pull request by andor0**
## Issue
https://app.clickup.com/t/30eeta4

### CODE REVIEW

**Comment by andor0** [comment]
> Should we add the needs-benchmarks label to update the benchmarks? They're quite outdated

It makes sense. Added `needs-benchmarks` label.

**Comment by dzmitry-lahoda** [comment]
would be resoanble to move script into relevant folder of code. beacause it benches only substrate runtimes, not anything else. it is not global by local. it would be monorepo approach.

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
thins what would be in multirepo? this script would be located into code. so monorepo is multirepo when people can think multi when needed:)

**Review by benluelo — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
could we run same script for bench checks and bench runs. so parameters passed with different count? that way check runs alwasy, and run never broken.

**Comment by andor0** [comment]
> would be resoanble to move script into relevant folder of code. beacause it benches only substrate runtimes, not anything else. it is not global by local. it would be monorepo approach.

done.

**Review by haroldsphinx — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Comment by andor0** [comment]
@mergify refresh

**Comment by andor0** [comment]
@mergify refresh

**Pull request merged**
