### PR TITLE
Rm build from hyperspace

### PR DESCRIPTION
**Pull request by blasrodri**
## Issue
*Please replace this line with either a link to the ClickUp issue, or a reference to the GitHub issue.*

## Description
*Please replace this line with info that is not in the ClickUp ticket, eg: "also bumps dependency foo version"*

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by blasrodri** [comment]
@seunlanlege can you please confirm that this is what you were referring to?
https://github.com/ComposableFi/composable/pull/2065#pullrequestreview-1150880249

**Comment by seunlanlege** [comment]
Yes it's similar, but in my comment we don't need polkadot launch running in the background. You only need the built composable node. So the cli is on the Composable node.

**Comment by blasrodri** [comment]
> Yes it's similar, but in my comment we don't need polkadot launch running in the background. You only need the built composable node. So the cli is on the Composable node.

For simplicity sake, can we just accept this solution for now and unblock us? I'm happy to discuss an improvement - but I don't even know where to start if it's adding a CLI for the composable node to be honest.

I've tested it using `docker run --platform linux/amd64 --rm -ti -u1000:1000 -p9944:9944 -p9188:9188 -p9988:9988 composablefi/composable-centauri:latest`

**Comment by seunlanlege** [comment]
> For simplicity sake, can we just accept this solution for now and unblock us? I'm happy to discuss an improvement - but I don't even know where to start if it's adding a CLI for the composable node to be honest.

We can discuss this on monday.

**Pull request closed without merging**
