### PR TITLE
[CU-2fjn8x3] Integration Tests for HAL-02 (Oracle)

### PR DESCRIPTION
**Pull request by Dom-Roth**
## Issue
https://app.clickup.com/t/2fjn8x3

## Description
Integration tests for HAL-02 issue.

Note: Skipping checklist point 5 due to the current Pablo testing issues.

## Checklist

- [x] Implemented all required test checks
- [x] Cleaned up all code
- [x] Implemented all tests
- [x] Added required documentation
- [ ] Ran the whole test suite without any failures
- [x] Ran `npm run lint` without any warnings / errors
- [ ] Created / Updated ClickUp report

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2fjn8x3 Test for: [Oracle] HAL-02 ORACLE SLASHING MECHANISM BYPASS](https://app.clickup.com/t/2fjn8x3)

**Review by Juliansv — DISMISSED** [review]

**Review by kollegian — DISMISSED** [review]

**Review by kollegian — APPROVED** [review]
LGTM

**Review by Juliansv — APPROVED** [review]

**Review by kollegian — APPROVED** [review]
LGTM

**Pull request merged**
