### PR TITLE
 cli tools on mac build, CI setup, dev docs update and clean up 

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
- ccw and subxt on mac
- simplified PR , contribution, dependencies guide
- removed scraper as better just gen some rust docs :)
- cleaned FE/Dali release mention, removed JS code moved to FE repo
- ensure that Bob and Fren in TF are set same way as manually to avoid overrides
- speed up docs build
- improved nix dx
- returned back nix comment (it is better than it was - it does not spams on each push, only when PR created once)
- ccw does generate projects, that up to CW tooling from CW people
- Codespace docs are super obsolete, and also copy paste from official, so removed most (except link to official guide and some our notes to work with our repo)
- we do not use nix arion too
- at stale clean ups bots

- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] I have linked Zenhub/Github or any other reference item if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [x] I have added at least one reviewer in reviewers list
- [x] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant features and processes required to release into production

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
@JafarAz any quesiton about deleted documents and updates? I purged a lot of garbage. And some processes we never followed and not following now.

**Comment by dzmitry-lahoda** [comment]
@fl-y just cc you - deleted all fe code from repo

**Comment by dzmitry-lahoda** [comment]
@fl-y @RustNinja @blasrodri my last fixes for Mac, I do not work on Mac release/ci/cache/etc as time consuming. ARM Linux works well.

**Review by RustNinja — APPROVED** [review]

**Comment by JafarAz** [comment]
sorry for the delayed response, no objections from me @dzmitry-lahoda

**Pull request merged**
