### PR TITLE
fix(ibc): Update ComposableFi centauri dependency + nix flake

### PR DESCRIPTION
**Pull request by RustNinja**
Required for merge:
- [x] `pr-workflow-check / draft-release-check` is ✅ success
- Other rules GitHub shows you, or can be read in [configuration](../terraform/github.com/branches.tf) 

Makes review faster:
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] Linked Zenhub/Github/Slack/etc reference if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] Added reviewer into `Reviewers`
- [x] I tagged(`@`) or used other form of notification of one person who I think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant features and processes required to release into production
- [x] Any dependency updates made, was done according guides from relevant dependency
- Clicking all checkboxes 
- Adding detailed description of changes when it feels appropriate (for example when PR is big)

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
chore(dependency): updated pallet-ibc and hyperspace versions

**Review by kkast — DISMISSED** [review]

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/actions/runs/5766898164/job/15635726624?pr=4024

**Comment by RustNinja** [comment]
> https://github.com/ComposableFi/composable/actions/runs/5766898164/job/15635726624?pr=4024

Thanks. DOne

**Review by dzmitry-lahoda — DISMISSED** [review]

**Review by blasrodri — DISMISSED** [review]

**Comment by dzmitry-lahoda** [comment]
I have run 4 prs total 5 times, and given 100% stability of previous runs, and that this pr fails 4 times always, i state something broken.

**Pull request closed without merging**
