### PR TITLE
[Merged by Bors] - [CU-2arav8f] Add a running of runtime-test in CI

### PR DESCRIPTION
**Pull request by Dom-Roth**
## Issue
https://app.clickup.com/t/2arav8f

## Description
Re- creation of  #885 because GitHub bugged out on a very old comment.
They were just finished and tested successfully, please review.

image

## Checklist

~~- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_~~
~~- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_~~

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2arav8f Add a running of 'integration-tests/runtime-tests' in CI](https://app.clickup.com/t/2arav8f)

**Review by andor0 — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by kollegian — APPROVED** [review]

**Comment by hussein-aitlahcen** [comment]
Are we going to add a 2h CI step?

**Comment by Dom-Roth** [comment]
Yes, it was discussed in a meeting with @KaiserKarel & @saadjhk (iirc) before.

**Comment by KaiserKarel** [comment]
> Yes, it was discussed with @KaiserKarel.
> I'll focus on optimizing the time the integration tests will take in the next Sprint.

@hussein-aitlahcen let's discuss Monday too; I'm afraid that if we don't merge this, we'll keep breaking stuff along the way. Alternatively we can run this check only on bors' staging branch, meaning we only incur the 2h test time when approvals and reviews are done.

**Comment by dzmitry-lahoda** [comment]
@Dom-Roth @hussein-aitlahcen @KaiserKarel can we enable, but only zero tests. so that test run, may be testing ping only. behind flag. and then @Dom-Roth will gate more and more tests which are fast/usefull/break often/stable(do not produce false positives)?

**Comment by Dom-Roth** [comment]
The tests in CI now run a shortened version, which takes about 10 minutes.
The whole CI step takes about 45 minutes, which is mainly due to compiling the release build.
@hussein-aitlahcen @KaiserKarel @dzmitry-lahoda @andor0

**Review by KaiserKarel — APPROVED** [review]

**Comment by KaiserKarel** [comment]
> The tests in CI now run a shortened version, which takes about 10 minutes. The whole CI step still takes about 45 minutes, which is mainly due to compiling the release build. @hussein-aitlahcen @KaiserKarel @dzmitry-lahoda @andor0

After Hussein's alterations to the workflows, we'll only compile release once, so this step will work better.

**Review by kollegian — APPROVED** [review]

**Pull request closed without merging**
