### PR TITLE
[CU-2trz77g] docs(frame): create assets readme

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/2trz77g

## Description
Create `README.md` for the assets pallet

## Checklist

- [X] Style, expression and spellchecking

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2trz77g Assets pallet readme](https://app.clickup.com/t/2trz77g)

**Review by dzmitry-lahoda — COMMENTED** [review]
is it supposed keep in sync with header in *.rs file?

**Comment by Martin-Kiss** [comment]
> is it supposed keep in sync with header in *.rs file?

No, I merely took its contents as it already had a good structure on which to base the rest of the readme. 
The idea of having readme content in *.rs files would be a discussion to have, I imagine it would work similarly to the extrinsics scraper. Regardless of the above, it really helps to have this present in some form to describe requirements and goals apart from code comments.

**Review by KaiserKarel — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
mergify refresh

**Comment by Martin-Kiss** [comment]
@Mergifyio refresh

**Pull request merged**
