### PR TITLE
feat(vamm): Add `close` functionality

### PR DESCRIPTION
**Pull request by Cardosaum**
## Issue
[CU-2y8mwr1](https://app.clickup.com/t/2y8mwr1)

## Description
Adds functionality to close a Vamm, as well as tests for this new feature.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2y8mwr1 Feature 13 (Close vamm)](https://app.clickup.com/t/2y8mwr1)

**Review by 0xangelo — CHANGES_REQUESTED** [review]
I think we're missing tests for other functionalities like `swap` and `swap_simulation` to check if those are blocked once a vAMM is closed

**Review by 0xangelo — APPROVED** [review]
LGTM :rocket:

**Comment by Cardosaum** [comment]
bors try

**Review by kevin-composable — APPROVED** [review]
Nice use of rstest - I definitely think that is a library worth exploring with our other pallets

**Pull request closed without merging**
