### PR TITLE
fix: incorrect binary name for composable-node

### PR DESCRIPTION
**Pull request by cor**

### CODE REVIEW

**Review by aeryz — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by hussein-aitlahcen — CHANGES_REQUESTED** [review]
Wait

**Comment by hussein-aitlahcen** [comment]
Let's check all occurence of the binary usage please

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
acala and basilisk and polkadot and statemine do not include node suffix into name

**Comment by cor** [comment]
> acala and basilisk and polkadot and statemine do not include node suffix into name

@dzmitry-lahoda yes this is true. The reason why I settled on composable-node for now is because it is a bit clearer within the context of our nix flake, since we have a lot of packages and I don't want there to be ambiguity. We can consider renaming it in a later commit if we really want to remove the suffix

**Comment by cor** [comment]
@mergify requeue

**Comment by cor** [comment]
@mergify update

**Pull request merged**
