### PR TITLE
fix(devnet): xc docker image user fix to run devent in docker and codespace

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
image

Required for merge:
- [x] `pr-workflow-check / draft-release-check` is ✅ success
- Other rules GitHub shows you, or can be read in [configuration](../terraform/github.com/branches.tf) 

Makes review faster:
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] Linked Zenhub/Github/Slack/etc reference if one exists https://github.com/F1bonacc1/process-compose/issues/84
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] Added reviewer into `Reviewers`
- [x] I tagged(`@`) or used other form of notification of one person who I think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant features and processes required to release into production
- [x] Any dependency updates made, was done according guides from relevant dependency
- Clicking all checkboxes 
- Adding detailed description of changes when it feels appropriate (for example when PR is big)

### CODE REVIEW

**Review by blasrodri — APPROVED** [review]
Can you tell me how to run the xc infra with this docker image?

**Comment by dzmitry-lahoda** [comment]
image

**Comment by dzmitry-lahoda** [comment]
@blasrodri you can run with tui like this 

 nix build "github:ComposableFi/composable/${{ github.ref }}#devnet-xc-image" --allow-import-from-derivation --extra-experimental-features "flakes nix-command" --no-sandbox --accept-flake-config --option sandbox relaxed \
            && docker load --input result && docker run -it --entrypoint bash devnet-xc:latest -c /bin/devnet-xc-fresh

**Comment by dzmitry-lahoda** [comment]
or if just plan logs `docker run -it devnet-xc:main` and it will run just background logs

**Comment by dzmitry-lahoda** [comment]
image

**Review by kkast — APPROVED** [review]

**Pull request merged**
