### PR TITLE
[PICA-298] Adding Oracle to Picasso

### PR DESCRIPTION
**Pull request by vimukthi-git**

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Task linked: [PICA-298 Get the Oracle onto runtime](https://app.clickup.com/t/20465559/PICA-298)

**Comment by andresmechali** [comment]
Requires rebasing for `nix run .#devnet-picasso` to work

**Review by andresmechali — APPROVED** [review]
Tested manually and looks good

**Review by andresmechali — APPROVED** [review]
🚀

**Pull request merged**
