### PR TITLE
[Merged by Bors] - chore(upgrade): latest polkadot-launch & update launch config

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**

### CODE REVIEW

**Review by benluelo — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by andor0 — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
you had old codeowners, likely rebased it would pass ealier. previosly only core team could do scirpts. so if hussen is pr, and karel approves - there is only one approval. so cannot merge. so now it is more fro scripts

**Pull request closed without merging**
