### PR TITLE
[CU-2qg8x0a] CI job to build lease-period-prolongator docker image

### PR DESCRIPTION
**Pull request by andor0**
## Issue
https://app.clickup.com/t/2qg8x0a

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2qg8x0a Create a CI job to build a Docker image with lease-period-prolongator](https://app.clickup.com/t/2qg8x0a)

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Review by alexkdefi — APPROVED** [review]
👍

**Comment by andor0** [comment]
@Mergifyio refresh

**Comment by andor0** [comment]
@Mergifyio refresh

**Pull request merged**
