### PR TITLE
Xcm ibc multihop transfer

### PR DESCRIPTION
**Pull request by RustNinja**
Draft PR that introduce pallet ibc xcm and callback trait.
Replace `MultiCurrency` struct to `MultiCurrencyWrapper` to register callback handler(`pallet-ibc-xcm`) and execute extra logic on xcm deposit success(because current version of MultiCurrency suggests only call back on failed deposit).
`Pallet-ibc-xcm` will check MultiLocation and compose the `memo` for ibc packet and call pallet ibc to emit new ibc packet for relayer.

- [ ] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [ ] I marked PR by `misc` label if it should not be in release notes
- [ ] I have linked Zenhub/Github or any other reference item if one exists
- [ ] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [ ] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [ ] I have added at least one reviewer in reviewers list
- [ ] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR
- [ ] I have proved that PR has no general regressions of relevant features and processes required to release into production

### CODE REVIEW

**Review by dzmitry-lahoda — DISMISSED** [review]

**Comment by dzmitry-lahoda** [comment]
IBC and XCM call it multihop, not batching.

There is batching in IBC, it means totally different thing.

**Comment by RustNinja** [comment]
> Tbh you may consider using simulator tests to develop this feature imho it can be useful

thanks. will use simulator. thank you 🫡

**Comment by dzmitry-lahoda** [comment]
is it obsolete?

**Comment by dzmitry-lahoda** [comment]
closing as it seems superseded

**Pull request closed without merging**
