### PR TITLE
0xangelo/merge main into escher

### PR DESCRIPTION
**Pull request by 0xangelo**
## Issue
Updates `escher` with the latest changes from `main`.

## Description
This is simply a merge of `main` into `escher`. It does not modify any files other than those of pallets related to the Escher project for compatibility with the latest changes in `main`.

### CODE REVIEW

**Comment by 0xangelo** [comment]
bors try

**Review by Cardosaum — APPROVED** [review]

**Review by nickkuk — APPROVED** [review]

**Review by benluelo — APPROVED** [review]

**Review by kevin-composable — APPROVED** [review]

**Review by Dom-Roth — APPROVED** [review]

**Comment by 0xangelo** [comment]
bors try

**Comment by 0xangelo** [comment]
bors try

**Review by Cardosaum — APPROVED** [review]

**Review by haroldsphinx — APPROVED** [review]

**Pull request closed without merging**
