### PR TITLE
Cosmwasm vm widget bootstrap PR

### PR DESCRIPTION
**Pull request by fl-y**
## Issue

[clickup](https://app.clickup.com/t/3rcjthy)
(kind of empty)

## Applied Changes

- added a test page that should be only visible in dev
- Applied ts to the repo
- Made tailwind work
- imported the vm & related methods
- confirmed the `vmSetup` working in test doc page

## Additional info

Was not developed using nix but running the docs using `npm run start` - the implications of what effect it had on the nix environment is unknown to me @cor 
This is the initial check to see if my approach to applying components to mdx files and imported components work in the  context of docusaurus.

### CODE REVIEW

**Comment by fl-y** [comment]
[test component](https://github.com/ComposableFi/composable/blob/joon/feat/scdi-widget/docs/docs/testSCDI/entry.mdx)

Created 2 'Wrapper' components that effectively expose the `vmShared` to child components to display on the screen,
or use the `VmExecute` component to execute a message using `vmShared`

contracts should be uploaded to `/static/wasm/` and loaded in a `VmWrapper` component's 'initOptions' prop
ex)
```jsx
<VmWrapper storageId='test' initOptions={{
		contractUrl: '/wasm/cw20_base.wasm',
		instantiateObj: {
			"name": "picasso",
			"symbol": "PICA",
			"decimals": 12,
			"initial_balances": [],
			"mint": {
				"minter": "0",
				"cap": null
			},
			"marketing": null
		}
	}}>
	{(vmShared) => {
	  //  logic using vmShared
	}}
</VmWrapper>
```

the `VmWrapper` component can be used with the same id without initOptions to be accessed in different places - only one is required to have the initOptions

After applying basic styles to `VmExecute` component it should be ready for use, since the `vmShared` can be exposed from any part of the mdx file and applied custom styling

**Review by cor — APPROVED** [review]
LGTM! I'm very excited to play around with this after the weekend

**Review by Martin-Kiss — APPROVED** [review]

**Review by andyjsbell — APPROVED** [review]
lgtm

**Review by PoisonPhang — APPROVED** [review]

**Comment by fl-y** [comment]
Closed because not GPG signed and new PR opened
#2534

**Pull request closed without merging**
