### PR TITLE
feat(cvm): adding/claryfing events/queries for tracking and indexing and state view in fe

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Mostly making FE/indexer work better.

Unified all interpreter events under single place and generated schema for it, so can parse out from json logs of cosmos sdk using generated types. Also added query to dump whole interpreter state in one query, super good for FE.

Removed generated schema from git and added docs how to generate schema manually.

Unified events prefix to be `cvm`.

Required for merge:
- [ ] `pr-workflow-check / draft-release-check` is ✅ success
- Other rules GitHub shows you, or can be read in [configuration](../terraform/github.com/branches.tf) 

Makes review faster:
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [ ] I marked PR by `misc` label if it should not be in release notes
- [ ] Linked Zenhub/Github/Slack/etc reference if one exists https://github.com/ComposableFi/composable/pull/4122
- [ ] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [ ] Added reviewer into `Reviewers`
- [ ] I tagged(`@`) or used other form of notification of one person who I think can handle best review of this PR
- [ ] I have proved that PR has no general regressions of relevant features and processes required to release into production
- [ ] Any dependency updates made, was done according guides from relevant dependency
- Clicking all checkboxes 
- Adding detailed description of changes when it feels appropriate (for example when PR is big)

### CODE REVIEW

**Review by mina86 — APPROVED** [review]

**Comment by blasrodri** [comment]
@dzmitry-lahoda can we add a doc for front end in which we show the lifecycle of a transaction, and the payloads that need to be input?

**Comment by dzmitry-lahoda** [comment]
i am working on this here https://github.com/ComposableFi/composable/pull/4122/files#diff-2bf8d4adfdff1203e268e7876e77d2832d3c23fcccec15edcf828cf7cc937bdd

**Comment by dzmitry-lahoda** [comment]
similar to this one i guess https://github.com/osmosis-labs/osmosis/tree/main/cosmwasm/contracts as example of docs (see in contracts README.md in folders)

**Comment by dzmitry-lahoda** [comment]
@blasrodri there is separate item docs are in progress

i am targeting  for docs of similar solution of osmosis cross chain swap with outpost and coin registry, but cvm is just more generalized

image

osmosis is succefull product adopted by several FE teams

**Pull request merged**
