### PR TITLE
[CU-200y9ka] Auction: generate a file with weights

### PR DESCRIPTION
**Pull request by andor0**
* Included benchmarks of pallet-dutch-auction in the runtime of node
* Updated a file with weights in pallet-dutch-auction
* Added a file with weights for dutch-auction in the runtime of node
* Temporary commented broken parts of tests of pallet-dutch-auction, those tests will update in the next PR

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-200y9ka Auction: generate a file with weights](https://app.clickup.com/t/200y9ka)

**Review by dzmitry-lahoda — DISMISSED** [review]

**Comment by KaiserKarel** [comment]
This seems to do a bit more than just weights, can you elaborate what else was added?

**Comment by andor0** [comment]
> This seems to do a bit more than just weights, can you elaborate what else was added?

Done.

**Review by KaiserKarel — DISMISSED** [review]

**Comment by KaiserKarel** [comment]
Need not say that the next PR needs to be added relatively soonish, to fix the tests.

**Comment by dzmitry-lahoda** [comment]
i am working on it

**Review by dzmitry-lahoda — DISMISSED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Pull request merged**
