### PR TITLE
Upgrade to polkadot-v0.9.16

### PR DESCRIPTION
**Pull request by seunlanlege**

### CODE REVIEW

**Comment by hussein-aitlahcen** [comment]
> Oh wow, I think you should merge instead of rebase

Just missed my rebase, rebased my work on main and then on top of this branch, will fix it

**Comment by hussein-aitlahcen** [comment]
```
[nix-shell:~/github/composable/composable]$ cargo build -p pallet-vault
   Compiling composable-traits v0.0.1 (/home/hussein/github/composable/composable/frame/composable-traits)
   Compiling pallet-vault v0.0.1 (/home/hussein/github/composable/composable/frame/vault)
    Finished dev [unoptimized + debuginfo] target(s) in 2.37s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-bonded-finance
   Compiling composable-traits v0.0.1 (/home/hussein/github/composable/composable/frame/composable-traits)
   Compiling pallet-bonded-finance v0.0.1 (/home/hussein/github/composable/composable/frame/bonded-finance)
    Finished dev [unoptimized + debuginfo] target(s) in 1.94s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-crowdloan-rewards
   Compiling pallet-crowdloan-rewards v0.0.1 (/home/hussein/github/composable/composable/frame/crowdloan-rewards)
    Finished dev [unoptimized + debuginfo] target(s) in 1.14s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-assets
   Compiling pallet-assets v0.0.1 (/home/hussein/github/composable/composable/frame/assets)
    Finished dev [unoptimized + debuginfo] target(s) in 1.09s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-vesting:0.0.1
   Compiling pallet-vesting v0.0.1 (/home/hussein/github/composable/composable/frame/vesting)
    Finished dev [unoptimized + debuginfo] target(s) in 0.93s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-curve-amm
   Compiling pallet-vault v0.0.1 (/home/hussein/github/composable/composable/frame/vault)
^[[A   Compiling pallet-curve-amm v0.0.1 (/home/hussein/github/composable/composable/frame/curve-amm)
    Finished dev [unoptimized + debuginfo] target(s) in 1.91s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-uniswap-v2
   Compiling pallet-uniswap-v2 v0.0.1 (/home/hussein/github/composable/composable/frame/uniswap-v2)
    Finished dev [unoptimized + debuginfo] target(s) in 1.05s

[nix-shell:~/github/composable/composable]$ cargo build -p pallet-call-filter
   Compiling pallet-call-filter v0.1.0 (/home/hussein/github/composable/composable/frame/call-filter)
    Finished dev [unoptimized + debuginfo] target(s) in 0.91s
```

We have this pallets compiling, let's try to fix all pallets and then upgrade mocks/tests/benchmarking

**Comment by hussein-aitlahcen** [comment]
Pallet not compilling that require non-trivial upgrades:
- democracy
- lending
- dutch-auction
- privilege
- ping

**Comment by andor0** [comment]
> Pallet not compilling that require non-trivial upgrades:
> 
> * democracy
> * lending
> * dutch-auction
> * privilege
> * ping

+ oracle ?

**Comment by andor0** [comment]
I'm updating `pallet-oracle`.

**Comment by hussein-aitlahcen** [comment]
Currently porting `privilege` and `democracy`

**Comment by hussein-aitlahcen** [comment]
@seunlanlege @KaiserKarel @andor0 I think we are not forced to port all of them to MaxEncodedLen right now https://github.com/paritytech/substrate/pull/10662

**Comment by seunlanlege** [comment]
> #[pallet::without_storage_info] is the trick.

glorious

**Comment by hussein-aitlahcen** [comment]
Note that this PR is not complete yet as [we probably want to migrate the scheduler](https://github.com/paritytech/substrate/pull/10356)

**Comment by hussein-aitlahcen** [comment]
- [x] Bump transaction_version https://github.com/paritytech/cumulus/pull/517
- [x] Adds pallet_preimage https://github.com/paritytech/substrate/pull/10356 
- [x] cumulus refactor
- https://github.com/paritytech/cumulus/pull/835
- https://github.com/paritytech/cumulus/pull/927
- https://github.com/paritytech/cumulus/pull/909
- https://github.com/paritytech/cumulus/pull/923

- [ ] Migrate scheduler https://github.com/paritytech/polkadot/pull/4166
- [ ] (Optional, doable later) Upgrade all pallets to the usage of **MaxEncodedLen**

**Pull request merged**
