### PR TITLE
fix: broken nixos-config link

### PR DESCRIPTION
**Pull request by cor**

### CODE REVIEW

**Review by aeryz — APPROVED** [review]
Amazing work!!

**Review by benluelo — APPROVED** [review]
this was a very large and hard to review PR, please keep them small in the future

**Comment by cor** [comment]
> this was a very large and hard to review PR, please keep them small in the future

Yeah sorry I tend to have some scope creep. Will try better next time

**Review by Martin-Kiss — APPROVED** [review]
LGTM 👍

**Pull request merged**
