### PR TITLE
[PBL-553] Subsquid: improve price caching and add an extra endpoint

### PR DESCRIPTION
**Pull request by andresmechali**
https://app.clickup.com/t/862jk6t8d

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Task linked: [PBL-553 Subsquid: get Coingecko price from different endpoint when unavailable, and improve caching](https://app.clickup.com/t/20465559/PBL-553)

**Review by bengalmozzi — APPROVED** [review]
LGTM

**Comment by nahyunbak** [comment]
LGTM

**Review by nahyunbak — APPROVED** [review]
LGTM

**Pull request merged**
