### PR TITLE
[CU-2bmuatd] Move pallets to dedicated section

### PR DESCRIPTION
**Pull request by cor**
## Issue
https://app.clickup.com/t/2bmuatd

## Description

~~Currently only works using the `doc_comment_include` fork of mdBook: https://github.com/rust-lang/mdBook/pull/1784. We hope it gets merged soon.~~ We now parse the pallet files for the documentation, the linked PR is no longer necessary.

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2bmuatd move pallet docs to obvious place](https://app.clickup.com/t/2bmuatd)

**Comment by dzmitry-lahoda** [comment]
pallets are scale, scale seems capture docs https://docs.substrate.io/v3/runtime/metadata/ . can we parse scale which is seems json and emebbed?

**Comment by benluelo** [comment]
> pallets are scale, scale seems capture docs https://docs.substrate.io/v3/runtime/metadata/ . can we parse scale which is seems json and emebbed?

This would require us to run the node and call the `state_getMetadata` rpc, as opposed to just static analysis of the files. Probably wouldn't work very well with CI or hot reloading the book while working on documentation

**Comment by dzmitry-lahoda** [comment]
not sure hot reloading is of value. and for extrinsic, i ok to run node. antway docs should be about releases api, not just main branch.

**Review by benluelo — DISMISSED** [review]

**Review by benluelo — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]

**Pull request merged**
