### PR TITLE
[Frontend][Picasso] - Fix Firefox issue with background blur.

### PR DESCRIPTION
**Pull request by easteregg**
## Issue
https://app.clickup.com/t/2k552em

## Description
Address Background blur fixes that won't work with firefox. 
Header and Modal backgrounds should be checked. 

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Review by saadjhk — APPROVED** [review]

**Review by andresmechali — APPROVED** [review]
Looks good to me and works as expected 🚀

**Comment by easteregg** [comment]
Closing in favor of: 
https://github.com/ComposableFi/composable/pull/1245

**Pull request closed without merging**
