### PR TITLE
[CU-2ejaj66] docs(mdbook ecosystem-development): replace current design & adjust summary

### PR DESCRIPTION
**Pull request by Martin-Roth**
## Issue
https://app.clickup.com/t/2ejaj66

## Description
replacing the current design, creating a new subpage

## Checklist

~~- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_~~
~~- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_~~

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2ejaj66 Mdbook changes](https://app.clickup.com/t/2ejaj66)

**Review by PoisonPhang — DISMISSED** [review]

**Review by 0xBrainjar2 — COMMENTED** [review]
would push up cosm wasm grants program and xcvm should be mentioned here @jafar can assist here

**Review by PoisonPhang — DISMISSED** [review]

**Review by cor — DISMISSED** [review]
LGTM

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by cor — APPROVED** [review]
LGTM

**Pull request merged**
