### PR TITLE
Switch to pull_request_target

### PR DESCRIPTION
**Pull request by KaiserKarel**
Normally, PRs from forks cannot access secrets. This allows them to do so. PRs that alter workflow files won't be able to access secrets still I think.

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Task linked: [SRE-534 PR from forks into Composable fail all jobs](https://app.clickup.com/t/20465559/SRE-534)

**Review by dzmitry-lahoda — APPROVED** [review]
thanks. so i guess secret part could be confirmed by sre or infra because if not people will have rotate keys.

**Comment by KaiserKarel** [comment]
> thanks. so i guess secret part could be confirmed by sre or infra because if not people will have rotate case.

So in this case, secrets will work in PRs from forks but the workflow code that is run is using base, not fork.

**Comment by dzmitry-lahoda** [comment]
ah, ok than.

**Comment by KaiserKarel** [comment]
I've checked that it is valid syntax, so unsure why the runners aren't picking it up. @radupopa2010 can you have a look?

**Comment by radupopa2010** [comment]
People suggest that  changing the name of the job requires a change in the config of "branch protection rules"

I see here se change the event name, so we might need to check the branch protection rules. 
I do not have admin access for this repo so I can't have a look; 
@KaiserKarel can you please check those?


https://github.com/orgs/community/discussions/26698#discussioncomment-3252954
_[Configuration of branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) is completely separate from your workflows. I assume that at some point in the past you’ve marked the previous jobs as required checks (step seven in the documentation, or search for “required status checks”). Once enabled, those jobs are required by name._

_You’ve changed job names, so you need to update the branch protection rule: Remove the old jobs, so waiting for jobs that don’t exist any more doesn’t block merging. And ideally add your new job (the non-matrix one) to that gets checked._

**Comment by KaiserKarel** [comment]
No that's not the case, the problem is that the workflow itself is not being spun up at all. If it was incorrect naming, we'd see it being spun up but the checks not being satisfied.

**Comment by KaiserKarel** [comment]
Do the runners have some log somewhere saying: syntax error in workflow file?

**Review by radupopa2010 — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]
LGTM

**Comment by radupopa2010** [comment]
> Do the runners have some log somewhere saying: syntax error in workflow file?

We use google logs exlorer
https://console.cloud.google.com/logs/query;cursorTimestamp=2023-01-20T11:34:24.087359931Z?referrer=search&project=composable-ci

The logs view is aggregated and we need to filter by VM instance id. To get that I need to run `gcloud compute instances describe`  on the name of the runner

 We use ephemeral runners and we have a bunch of names like `ghr-2aa49e`.   When running a job one can pickup the name of the runner from the setup job , e.g.
`Runner name: 'ghr-7a252e'` ; 

Since VM is not running anymore it's difficult for me to pull that ID now.

**Comment by KaiserKarel** [comment]
Luckily we figured out the issue, but indeed nice to be able to store those logs.

**Pull request merged**
