### PR TITLE
[CU-1xphzem] Port Acala's integration tests

### PR DESCRIPTION
**Pull request by andor0**

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-1xphzem Port Acala's integration tests](https://app.clickup.com/t/1xphzem)

**Comment by KaiserKarel** [comment]
@andor0 can we fix the ci check and merge this? :)

**Comment by dzmitry-lahoda** [comment]
it was work going before andrey switched to devops things and I switched to xmp free liquidation. will enact it as soon as done with that part.

**Comment by KaiserKarel** [comment]
I can have a look as well and get this merged

**Review by dzmitry-lahoda — DISMISSED** [review]

**Comment by KaiserKarel** [comment]
@andor0 can we merge this/what more do we need here?

**Comment by andor0** [comment]
> I can have a look as well and get this merged

Cleaned up comments. Please review.

**Review by KaiserKarel — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Pull request merged**
