### PR TITLE
[CU-3baupye] emit PriceChanged event when price changes on selected assets

### PR DESCRIPTION
**Pull request by andresmechali**
https://app.clickup.com/t/3baupye

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3baupye Emit `PriceChanged` event on `Oracle` pallet](https://app.clickup.com/t/3baupye)

**Review by Dom-Roth — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]

**Review by PoisonPhang — APPROVED** [review]
LGTM!
One NIT in testing

**Review by KaiserKarel — APPROVED** [review]

**Comment by vimukthi-git** [comment]
@andresmechali We use Mergify now, let's not trigger the bors :)

**Comment by andresmechali** [comment]
@Mergifyio refresh

**Comment by KaiserKarel** [comment]
@Mergifyio refresh

**Pull request merged**
