### PR TITLE
ci(devnet): dotsama devenet package (full devnet minus hermes/osmosis)

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Required for merge:
- [x] `pr-workflow-check / draft-release-check` is ✅ success
- Other rules GitHub shows you, or can be read in [configuration](../terraform/github.com/branches.tf) 

Makes review faster:
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] Linked Zenhub/Github/Slack/etc reference if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] Added reviewer into `Reviewers`
- [x] I tagged(`@`) or used other form of notification of one person who I think can handle best review of this PR
- [x] I have proved that PR has no general regressions of relevant features and processes required to release into production
- [x] Any dependency updates made, was done according guides from relevant dependency
- Clicking all checkboxes 
- Adding detailed description of changes when it feels appropriate (for example when PR is big)

### CODE REVIEW

**Comment by kkast** [comment]
lets wait for new pr if it passes old ci checks, then we will merge this since it changes cis also

**Review by kkast — CHANGES_REQUESTED** [review]
i will approve after see that old ci fails or passes.

**Comment by dzmitry-lahoda** [comment]
evidently old ci passes.

**Comment by kkast** [comment]
now it passes. before this commit it wasnt https://github.com/ComposableFi/composable/commit/df0b54e3bc72c1499169c9d920c128b5f8c14d4f. lets still merge this since osmosis build shouldnt affect our tests

**Review by kkast — APPROVED** [review]

**Review by RustNinja — APPROVED** [review]

**Pull request merged**
