### PR TITLE
Picasso -  Release 2 -  Enable transfer page

### PR DESCRIPTION
**Pull request by easteregg**
## Issue
https://app.clickup.com/t/375yx80

## Description 

This PR will bring back transfers page, with the following: 
- BYOG dropdown functionality.
- Statemine & Kusama transfers with the supported assets.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-375yx80 [Picasso] - Enable Transfer Page](https://app.clickup.com/t/375yx80)

**Review by saadjhk — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]

**Comment by easteregg** [comment]
@mergifyio refresh

**Comment by easteregg** [comment]
@mergifyio refresh

**Comment by easteregg** [comment]
@mergifyio refresh

**Review by andresmechali — APPROVED** [review]

**Pull request merged**
