### PR TITLE
[CU-3rr148e] fix update vesting schedules

### PR DESCRIPTION
**Pull request by andresmechali**
## Issue

https://app.clickup.com/t/3rr148e

### CODE REVIEW

**Review by vimukthi-git — APPROVED** [review]
LGTM

**Review by vimukthi-git — APPROVED** [review]
LGTM

**Review by KaiserKarel — APPROVED** [review]

**Review by blasrodri — APPROVED** [review]
LGTM

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-3rr148e On Vesting::update_vesting_schedules, use ScheduleInfo instead of Schedule](https://app.clickup.com/t/3rr148e)

**Pull request merged**
