### PR TITLE
docs: tell people to check their nix version

### PR DESCRIPTION
**Pull request by cor**
## Description
Our flakes do not work on old nix versions, so we should inform people to check their version

### CODE REVIEW

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@Mergifyio rebase

**Comment by KaiserKarel** [comment]
@Mergifyio requeue

**Comment by cor** [comment]
@Mergifyio requeue

**Comment by cor** [comment]
@mergify requeue

**Review by Martin-Kiss — APPROVED** [review]

**Pull request closed without merging**
