### PR TITLE
[CU-2r1q74q] docs(book): edit techstack and crowdloan page on mdbook

### PR DESCRIPTION
**Pull request by Martin-Kiss**
## Issue
https://app.clickup.com/t/2r1q74q

## Description
Update content of the technical stack and Picasso crowdloan page.

## Checklist
- [X] text
- [X] Images

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2r1q74q Edit tech stack Page on Mdbook](https://app.clickup.com/t/2r1q74q)

**Review by PoisonPhang — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by 0xBrainjar2 — APPROVED** [review]

**Review by Dom-Roth — APPROVED** [review]

**Review by hussein-aitlahcen — APPROVED** [review]

**Comment by Martin-Kiss** [comment]
@Mergifyio refresh

**Comment by Martin-Kiss** [comment]
@Mergifyio refresh

**Comment by Martin-Kiss** [comment]
@Mergifyio refresh

**Pull request merged**
