### PR TITLE
[CU-1vzab3b] Added TryIntoValidated

### PR DESCRIPTION
**Pull request by PoisonPhang**
This does type inference just fine but should be tested with #647 before leaving draft.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-1vzab3b Introduce a new Validated helper](https://app.clickup.com/t/1vzab3b)

**Review by benluelo — DISMISSED** [review]

**Review by dzmitry-lahoda — COMMENTED** [review]
if do just try into and prelude will rust solve types without explicit casts than?

**Comment by benluelo** [comment]
> if do just try into and prelude will rust solve types without explicit casts than?

As long as the validated type is used somewhere with a concrete type (i.e. a function or method) it should be fine. If you're just setting a variable, you'll have to supply type annotations for the `U` type.

```rust
let t: Validated<_, SomeType> = value.try_into_validated().unwrap();
```

Perhaps we could put the `U` parameter on the method? That way it could be specified like this:

```rust
let t = value.try_into_validated::<SomeType>().unwrap();
```

**Comment by hussein-aitlahcen** [comment]
> > if do just try into and prelude will rust solve types without explicit casts than?
> 
> As long as the validated type is used somewhere with a concrete type (i.e. a function or method) it should be fine. If you're just setting a variable, you'll have to supply type annotations for the `U` type.
> 
> ```rust
> let t: Validated<_, SomeType> = value.try_into_validated().unwrap();
> ```
> 
> Perhaps we could put the `U` parameter on the method? That way it could be specified like this:
> 
> ```rust
> let t = value.try_into_validated::<SomeType>().unwrap();
> ```

Adding U as parameter would be nifty 👍

**Comment by benluelo** [comment]
> > > if do just try into and prelude will rust solve types without explicit casts than?
> > 
> > 
> > As long as the validated type is used somewhere with a concrete type (i.e. a function or method) it should be fine. If you're just setting a variable, you'll have to supply type annotations for the `U` type.
> > ```rust
> > let t: Validated<_, SomeType> = value.try_into_validated().unwrap();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Perhaps we could put the `U` parameter on the method? That way it could be specified like this:
> > ```rust
> > let t = value.try_into_validated::<SomeType>().unwrap();
> > ```
> 
> Adding U as parameter would be nifty +1

I believe this would work, haven't tested it:

```rust
pub trait TryIntoValidated<T> {
	fn try_into_validated<U: Validate<T, U>>(self) -> Result<Validated<T, U>, &'static str>;
}

impl<T> TryIntoValidated<T> for T
{
	fn try_into_validated<U: Validate<T, U>>(self) -> Result<Validated<T, U>, &'static str> {
		Validated::new(self)
	}
}
```

**Review by benluelo — APPROVED** [review]

**Comment by PoisonPhang** [comment]
> > > > if do just try into and prelude will rust solve types without explicit casts than?
> > > 
> > > 
> > > As long as the validated type is used somewhere with a concrete type (i.e. a function or method) it should be fine. If you're just setting a variable, you'll have to supply type annotations for the `U` type.
> > > ```rust
> > > let t: Validated<_, SomeType> = value.try_into_validated().unwrap();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Perhaps we could put the `U` parameter on the method? That way it could be specified like this:
> > > ```rust
> > > let t = value.try_into_validated::<SomeType>().unwrap();
> > > ```
> > 
> > 
> > Adding U as parameter would be nifty +1
> 
> I believe this would work, haven't tested it:
> 
> ```rust
> pub trait TryIntoValidated<T> {
> 	fn try_into_validated<U: Validate<T, U>>(self) -> Result<Validated<T, U>, &'static str>;
> }
> 
> impl<T> TryIntoValidated<T> for T {
> 	fn try_into_validated<U: Validate<T, U>>(self) -> Result<Validated<T, U>, &'static str> {
> 		Validated::new(self)
> 	}
> }
> ```
> 
> I think this would also make more sense since we implement the trait for all types, and then the method itself is generic over the validator

Yep, that works and is quite a bit cleaner. Thanks

**Review by hussein-aitlahcen — APPROVED** [review]

**Pull request merged**
