### PR TITLE
[CU-1n09gg7] Add coverage job to CI

### PR DESCRIPTION
**Pull request by Br1ght0ne**

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-1n09gg7 Add code coverage to the CI](https://app.clickup.com/t/1n09gg7)

**Comment by hussein-aitlahcen** [comment]
Cool! @Br1ght0ne can we rebase this on `main` instead of develop please :)?

**Comment by Br1ght0ne** [comment]
@hussein-aitlahcen Rebased.

**Review by flipchan — DISMISSED** [review]
lgtm

**Comment by Br1ght0ne** [comment]
Please consider merging or closing this PR soon.

**Review by dzmitry-lahoda — APPROVED** [review]

**Pull request closed without merging**
