### PR TITLE
[CU-37k4a66] Removed dependance on staking from pablo

### PR DESCRIPTION
**Pull request by PoisonPhang**
## Issue

[[CU-37k4a66]](https://app.clickup.com/t/37k4a66)

## Additional Changes

To fix the bug described on ClickUp, I have removed Pablo's dependency on pallet-staking.

Updated fee handling so in amount and fee are transferred to pool account.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-37k4a66 [Integration Bug] Constant Pool creation not working as expected](https://app.clickup.com/t/37k4a66)

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]
LGTM

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-334h805 [RESEARCH] Assess decoupling staking rewards from pablo dex](https://app.clickup.com/t/334h805)

**Comment by PoisonPhang** [comment]
@Mergifyio refresh

**Pull request merged**
