### PR TITLE
Update features of integration-tests

### PR DESCRIPTION
**Pull request by andor0**

### CODE REVIEW

**Review by dzmitry-lahoda — DISMISSED** [review]
for some reason this pallet has benchmarks optional. weird

**Comment by vivekvpandya** [comment]
So I assume issue was due to not including society pallet before. Is that correct ?

**Comment by dzmitry-lahoda** [comment]
und check and test things were working. but seems bench somehow references code more directly

**Comment by dzmitry-lahoda** [comment]
but, why would we make ci run longer by running bench mode on non relevant crate for that? :)

**Comment by andor0** [comment]
> So I assume issue was due to not including society pallet before. Is that correct ?

Yes, that is. Needed society pallet with `runtime-benchmarks` feature.

**Review by seunlanlege — APPROVED** [review]

**Comment by andor0** [comment]
> but, why would we make ci run longer by running bench mode on non relevant crate for that? :)

`integration-tests` crate excluded from benchmarks build.

**Review by dzmitry-lahoda — APPROVED** [review]

**Pull request merged**
