### PR TITLE
[CU-2rb73xg] Integration Tests - Launch Plan Phase 1

### PR DESCRIPTION
**Pull request by Dom-Roth**
## Issue
https://app.clickup.com/t/2rb73xg

## Description
Integrated by adding the Tag `LAUNCH` to the test required by these.

## Checklist

- [x] Implemented all tests
- [x] Implemented all required test checks
- [x] Cleaned up all code
- [x] Added required documentation
- [x] Ran the whole test suite without any failures
- [x] Ran `npm run lint` without any warnings / errors
- [x] Created / Updated ClickUp report

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2rb73xg Test Suite - Phase 1](https://app.clickup.com/t/2rb73xg)

**Comment by Dom-Roth** [comment]
Setting back to draft for now. Because it is currently missing a test for this condition:
> Users can see their crowdloan but not claim

**Review by vimukthi-git — APPROVED** [review]
So I guess the actual tests for "PICA for gas" etc needs to be written later?

**Comment by Dom-Roth** [comment]
> So I guess the actual tests for "PICA for gas" etc needs to be written later?

Yes, since all of the pallets that'll will additional tests are pallets that are on my "Tests about to check" list anyway. So i'll take care of them, when i take care of that.

The only exception to this is the additional crowdloan test. Since the crowdloan isn't on my check list, I'll take care of it within this PR as well.

**Review by kollegian — APPROVED** [review]

**Pull request merged**
