### PR TITLE
fix(picasso-runtime) percentile to 50 for initial payment

### PR DESCRIPTION
**Pull request by andyjsbell**
## Issue

https://app.clickup.com/t/3qnp3ya

## Additional Changes

NA

## Checklist

- [ ] Updated the rust/typescript docs.
- [ ] Updated the `docs/`.

### CODE REVIEW

**Comment by PoisonPhang** [comment]
The failing unit test `dex::tests::constant_product::compute_redeemed_for_lp::no_unexpected_errors_in_range` is unrelated to this change.
This means the test is flaky and should probably be ignored until I can resolve that. Gong to create a tasks on ClickUp and link that here.

For now, see if running it again will pass. If not we can `ignore` it in this PR.

**Review by PoisonPhang — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]
LGTM

**Review by KaiserKarel — APPROVED** [review]

**Comment by KaiserKarel** [comment]
@andyjsbell I think this needs a rebase to apply Vim's removal of flaky tests

**Comment by vimukthi-git** [comment]
@mergifyio refresh

**Pull request merged**
