### PR TITLE
#2kre8qx Pablo - Refreshing a page on Pablo looses wallet connection

### PR DESCRIPTION
**Pull request by saadjhk**
## Issue
Refreshing the page loses wallet connection on pablo FE.

## Description
Utilizing localStorage api from the browser to storage connected account, and then restoring it when the user lands on the app again.

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2kre8qx Pablo - Refreshing a page on Pablo looses wallet connection](https://app.clickup.com/t/2kre8qx)

**Review by easteregg — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]

**Pull request merged**
