### PR TITLE
#wip #draft process items RFC

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Signed-off-by: Dzmitry Lahoda <dzmitry@lahoda.pro>

## Checklist

- [ ] Updated the rust/typescript docs.
- [ ] Updated the `docs/`.

### CODE REVIEW

**Comment by andyjsbell** [comment]
@dzmitry-lahoda thanks for this.  We are in the process of aligning CU/GH with our work practices.  Let's use this RFC as the base for this.  I will probably review/commit to this PR during this process so please keep this open and in draft for the time being 👍

**Comment by dzmitry-lahoda** [comment]
(

> @dzmitry-lahoda thanks for this. We are in the process of aligning CU/GH with our work practices. Let's use this RFC as the base for this. I will probably review/commit to this PR during this process so please keep this open and in draft for the time being 👍

:)) In the end, there is todo to described on how I align with SAFE/Scrum (so it is not require any). Core CU item flow is more or less cleaned (so no Grammarly yet on it), but why and consideration and Ghant change through experiment and alignment with SAFE/Scrum is not clarified.

And importantly, it does not specifies any hierarchy or task structure (milestones, features) - actually it consider all items to be just items (so need to clarify how `long` term running milestone/feature is same as small feature).

Also need to clarify how PO/PMs can act as `manual labour for making our Ghant Chart` because all tools sucks to automate this (specifically LibreOffice only tool I used which does Ghant Chart right).

And also how to compose items flow with tags is not clarified too (so as with hierarchy - there is no need to use tags, but would be good to use)

**Comment by andyjsbell** [comment]
@dzmitry-lahoda I thought we agreed to leave this open, why did you close it?

**Comment by dzmitry-lahoda** [comment]
It was opened for a while so. I closed it because
1. Needs updates regarding ownership definition (so task is always owned directly or indirectly and we can always sure progresses by hierarchy of ownership).
2. Updates to handling ETA, mentioned and comments.
3. Other updates I recalled to make all rules consistent, non self contradictory and allow to be run (so the goal is clear to move forward the tasks chart and able resolve any state case) 

And that no solves then education people about. And lack of interest in topic. And there is no incentive to handle that. So nothing grounds investment into it more then I did (more then some time to draft).

**Comment by dzmitry-lahoda** [comment]
@andyjsbell and the document will be 3x size. 1. rules 2. reasoning 3. examples. 
i am pretty sure it is possible to make it consistent and teach people. so there should be acceptance we want to work like that - specifically, people should care to review or comment on it.

**Comment by dzmitry-lahoda** [comment]
if we 100% defined work to be done. we create placeholder task for sure in proper hierarchy and with proper tags/fields because we would do it 100% and then fill details.

**Comment by dzmitry-lahoda** [comment]
export day to day report of activity of subordinate to manager

**Pull request closed without merging**
