### PR TITLE
Refactor datastructures

### PR DESCRIPTION
**Pull request by benluelo**
https://app.clickup.com/t/2xbqu5p

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2xbqu5p Refactor Staking Datastructures](https://app.clickup.com/t/2xbqu5p)

**Comment by cor** [comment]
The FMT changes look good to me 👍🏻

**Review by vimukthi-git — APPROVED** [review]
LGTM! Nice refactoring 🙂

**Review by PoisonPhang — APPROVED** [review]

**Review by cor — APPROVED** [review]
I approve the nix changes

**Comment by benluelo** [comment]
@mergify refresh

**Pull request merged**
