### PR TITLE
Prefer `x.to_string()` over `format!("{}", x)`

### PR DESCRIPTION
**Pull request by mina86**
Rust is currently unable to optimise `format!("{}", x)` invocations which are noticeably slower than calls to `to_string` method.  Prefer the latter.

- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] I have linked Zenhub/Github or any other reference item if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [ ] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [x] I have added at least one reviewer in reviewers list
- [x] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR
- [ ] I have proved that PR has no general regressions of relevant features and processes required to release into production

### CODE REVIEW

**Comment by mina86** [comment]
I don’t believe so.

**Comment by blasrodri** [comment]
Do you have any source for this?

**Review by blasrodri — DISMISSED** [review]

**Comment by mina86** [comment]
> Do you have any source for this?

https://github.com/near/nearcore/pull/7568#issuecomment-1239344087

**Review by blasrodri — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
- no_std compile fails https://github.com/ComposableFi/composable/actions/runs/5203314874/jobs/9386001582?pr=3671
- rust fmt fails https://github.com/ComposableFi/composable/actions/runs/5203314874/jobs/9386001355?pr=3671
cc @mina86

**Comment by mina86** [comment]
> ```
> docker-layer-devnet-picasso> Probing EDD (edd=off to disable)... oc./run-vm: line 5:    12 Segmentation fault 
> ```

Use Rust, they said, it’s memory safe, they said… ;)

**Comment by dzmitry-lahoda** [comment]
> docker-layer-devnet-picasso> Probing EDD (edd=off to dis

retry job. it is random docker image build fail. will look later.

**Pull request closed without merging**
