### PR TITLE
Ben/merge ben clippy into main

### PR DESCRIPTION
**Pull request by benluelo**

### CODE REVIEW

**Comment by benluelo** [comment]
Linter is failing because of the disallowed methods and types. Not sure what to do about those

**Review by dzmitry-lahoda — DISMISSED** [review]

**Comment by KaiserKarel** [comment]
@benluelo will continue checking the unwraps/disallowed types this weeked. Feel free to fix some yourself as well, or DM me with questions.

**Review by hussein-aitlahcen — APPROVED** [review]
This is insane thank you so much :)

**Review by KaiserKarel — DISMISSED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
@benluelo i have some success to sign old commits via https://stackoverflow.com/a/63884006/173073

**Comment by benluelo** [comment]
All the commits should be signed now (I've also turned on GPG signing for all future commits as well)

**Review by hussein-aitlahcen — DISMISSED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Pull request merged**
