### PR TITLE
Moonbase alpha parachain

### PR DESCRIPTION
**Pull request by RustNinja**
- [x] PR title is my best effort to provide summary of changes and has clear text to be part of release notes 
- [x] I marked PR by `misc` label if it should not be in release notes
- [x] I have linked Zenhub/Github or any other reference item if one exists
- [x] I was clear on what type of deployment required to release my changes (node, runtime, contract, indexer, on chain operation, frontend, infrastructure) if any in PR title or description
- [x] I waited and did best effort for `pr-workflow-check / draft-release-check` to finish with success(green check mark) with my changes
- [x] I have added at least one reviewer in reviewers list
- [x] I tagged(@) or used other form of notification of one person who I think can handle best review of this PR

### CODE REVIEW

**Review by dzmitry-lahoda — APPROVED** [review]
not sure, really para-2150-wasm file is needed? cause it is not needed for other relays

**Comment by RustNinja** [comment]
> not sure, really para-2150-wasm file is needed? cause it is not needed for other relays

there is step number 2
https://docs.moonbeam.network/builders/interoperability/xcm/xc-integration/#moonbase-alpha-xcm

**Comment by dzmitry-lahoda** [comment]
was testing conducted and this PR can be dismissed?

**Comment by RustNinja** [comment]
> @RustNinja is this to be closed as other one was produced?

yes.. thanks.

**Pull request closed without merging**
