### PR TITLE
[Merged by Bors] - [Picasso][Pablo] - Add version number to pages

### PR DESCRIPTION
**Pull request by easteregg**
## Issue
To detect proper version changes, add a capability to display the build date under each page. 

## Description
For QA purposes, this feature is needed. 

## Checklist

- [ ] I have updated the cargo docs to reflect changes made by this PR _(if applicable)_
- [ ] I have updated the `book/` to reflect changes made by this PR _(if applicable)_

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-2u494az Add Version number in bottom right of the screen](https://app.clickup.com/t/2u494az)

**Review by andresmechali — APPROVED** [review]
LGTM

**Review by saadjhk — APPROVED** [review]

**Comment by saadjhk** [comment]
LGTM

**Pull request closed without merging**
