### PR TITLE
#cu-86698qm63 ldd was fixed by #zombienet in 3rd party they use

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
- container runs well
- local blocks produced
- had to add timeout to devnet run to debug easy
- devnet runs in test again on ci
- https://github.com/paritytech/zombienet/pull/683 (fix for other binaries)

### CODE REVIEW

**Review by cor — APPROVED** [review]
Fixes the LLD issue 👍🏻

**Review by Dom-Roth — APPROVED** [review]
LGTM!

**Review by obsessed-cake — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
@Mergify refresh

**Comment by dzmitry-lahoda** [comment]
@Mergifyio refresh

**Review by KaiserKarel — APPROVED** [review]

**Pull request merged**
