### PR TITLE
[CU-34qhnj1] add lend and unlend functions to Lending pallet

### PR DESCRIPTION
**Pull request by kkast**
add lend and unlend functions to Lending pallet, fixing tests

### CODE REVIEW

**Comment by benluelo** [comment]
`lend` and `unlend` are pretty vague - perhaps something like `deposit` and `withdraw` (which is the same as the underlying vault functions called in these extrinsics)

Also, what's the purpose of these extrinsics? The relevant clickup ticket is empty: https://app.clickup.com/t/34qhnj1

**Comment by benluelo** [comment]
Also please run `nix run ".#fmt"`

**Comment by kkast** [comment]
> `lend` and `unlend` are pretty vague - perhaps something like `deposit` and `withdraw` (which is the same as the underlying vault functions called in these extrinsics)
> 
> Also, what's the purpose of these extrinsics? The relevant clickup ticket is empty: https://app.clickup.com/t/34qhnj1

the idea to use lend and unlend instead of deposit and withdraw i think is because there is already deposit_collateral and withdraw_collateral. rn, Lending pallet doesnt have extrinsic to work with vault. it needs to use vault extrinsics to deposit or withdraw. we want to have these functions here in order to pause them if necessary.

**Comment by benluelo** [comment]
> > `lend` and `unlend` are pretty vague - perhaps something like `deposit` and `withdraw` (which is the same as the underlying vault functions called in these extrinsics)
> > Also, what's the purpose of these extrinsics? The relevant clickup ticket is empty: https://app.clickup.com/t/34qhnj1
> 
> the idea to use lend and unlend instead of deposit and withdraw i think is because there is already deposit_collateral and withdraw_collateral. rn, Lending pallet doesnt have extrinsic to work with vault. it needs to use vault extrinsics to deposit or withdraw. we want to have these functions here in order to pause them if necessary.

makes sense, but I see no reason why they couldn't be called `vault_deposit` and `vault_withdraw` though. Perhaps @kevin-composable can comment here

> we want to have these functions here in order to pause them if necessary.
Maybe adding pausing functionality would be good?

**Comment by dzmitry-lahoda** [comment]
imho it is good to have pallet methods for that. so i never seen such naming before. can we have diffeerent names which are more common?

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by kevin-aftermath — COMMENTED** [review]
This looks perfect; `vault_deposit` and `vault_withdraw` sound good to me

**Review by kevin-composable — COMMENTED** [review]
This looks perfect; `vault_deposit` and `vault_withdraw` sound good to me

**Review by kevin-composable — APPROVED** [review]

**Review by vimukthi-git — APPROVED** [review]
LGTM :) Though I'm unable to provide much in-depth review or insight without a design/spec or details in the task linked.

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-34qhnj1 Add vault_deposit + vault_withdraw extrinsics](https://app.clickup.com/t/34qhnj1)

**Pull request merged**
