### PR TITLE
Migrate ansible away to SRE repo and clean up older unused SRE scripts

### PR DESCRIPTION
**Pull request by haroldsphinx**
- Migrate all ansoble playbooks to SRE Repo
- Remove old sre scripts

### CODE REVIEW

**Review by dzmitry-lahoda — APPROVED** [review]

**Review by Martin-Kiss — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Comment by hussein-aitlahcen** [comment]
@mergifyio refresh

**Comment by hussein-aitlahcen** [comment]
@mergifyio requeue

**Comment by hussein-aitlahcen** [comment]
Seems to be stuck trying to unstuck

**Comment by hussein-aitlahcen** [comment]
@mergifyio requeue

**Pull request closed without merging**
