### PR TITLE
Bors 🤖 do squash

### PR DESCRIPTION
**Pull request by vimukthi-git**
Bors 🤖 do squash

### CODE REVIEW

**Comment by vimukthi-git** [comment]
bors+

**Review by dzmitry-lahoda — DISMISSED** [review]

**Review by andor0 — DISMISSED** [review]

**Comment by KaiserKarel** [comment]
Moving discussion from slack to here. The question is; do we want to squash PRs?

**Comment by vimukthi-git** [comment]
May be take a vote? We all agree the current state is not good, just need a solution that everyone commits to. Options are
- squash with github default
- rebase on your branch before merging with a neat history (if I understand correctly): a bit hard to enforce I guess though.

**Comment by benluelo** [comment]
We could add checking the history to the review process, although it won't be possible to enforce that with a check (other than checking every commit with the CI pipeline, but I'm not sure if that would be worth it)

**Comment by benluelo** [comment]
I think we should set standards for commit content & messages, whatever those standards are I don't personally care but if we all use the same format then it would make reviewing a lot easier

**Comment by KaiserKarel** [comment]
> I think we should set standards for commit content & messages, whatever those standards are I don't personally care but if we all use the same format then it would make reviewing a lot easier

There are CI checks for message standards

**Comment by benluelo** [comment]
> There are CI checks for message standards

That's sweet, I didn't know that! I think integrating something like that would be super helpful, help us all build better git habits

**Comment by vimukthi-git** [comment]
@hussein-aitlahcen @benluelo @KaiserKarel @dzmitry-lahoda Shall we make this change for now until the proper rules/system can be set up (which just resets things to previous state before integrating bors. I'm ok with what @benluelo suggests for later though)? Longer we wait the more our main branch looks untidy (which for me is the main concern). 

Otherwise I can close this PR also.

**Review by PoisonPhang — DISMISSED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Review by PoisonPhang — DISMISSED** [review]

**Review by benluelo — APPROVED** [review]

**Review by KaiserKarel — APPROVED** [review]

**Comment by vimukthi-git** [comment]
Closing this to reopen as another PR to fix the bors problem

**Pull request closed without merging**
