### PR TITLE
CU-1pkgdr4 - latest subxt client for `picasso` with `develop` feature

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**

### CODE REVIEW

**Comment by ComposableFiB0t** [comment]
Task linked: [CU-1pkgdr4 Generate latest subxt client](https://app.clickup.com/t/1pkgdr4)

**Review by dzmitry-lahoda — APPROVED** [review]
is .scale file generated from build? is client supposed to work with latest scale info?
could we remove scale from git? and if we will not remove, will we see build issue if scale file became old?

oh, just tricky was to ask if can gitignore scale to have less issues to have incompatible client

**Comment by hussein-aitlahcen** [comment]
> is .scale file generated from build? is client supposed to work with latest scale info? could we remove scale from git? and if we will not remove, will we see build issue if scale file became old?
> 
> oh, just tricky was to ask if can gitignore scale to have less issues to have incompatible client

The scale is fetched from the node after compilation. I think we need a separate repo once the devnet is ready. The CI will deploy the devnet, fetch the `.scale` and commit to the `composable-subxt-client` repo perhaps?

**Comment by hussein-aitlahcen** [comment]
Or we could force developers to maintain valid `.scale` by checking them in the CI. But this require anyone to build the node + regenerate...

**Review by andor0 — APPROVED** [review]

**Pull request closed without merging**
